language: ruby

sudo: false

before_install:
  - gem update --remote bundler
  - gem update --system
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.13.7

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3
  - rbx-2
  - ruby-head

bundler_args: --without development --jobs=3 --retry=3

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
