language: ruby

sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2
  - ruby-head

bundler_args: --without development --jobs=3 --retry=3

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
